name: release
on:
  push:
    tags:
      - v*.*.*

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: 1.21.x
      - name: Build
        run: |
          ARCH=amd64 make tarball
          ARCH=arm64 make tarball
          ARCH=amd64 OS=darwin make tarball
          ARCH=arm64 OS=darwin make tarball
        env:
          VERSION: ${{ github.ref_name }}
      - name: Release
        run: |
          gh release create ${{ github.ref_name }} *.tar.gz \
            --title ${{ github.ref_name }} \
            --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
